### ISSUE TITLE
[FEATURE REQUEST] - Delay Between Zones and Cycles

### ISSUE THREAD

**Issue by TheRealSimonMlr** [MTry/homebridge-smart-irrigation#34]
At first, 
thank you for all the hard work you put into the plugin.

**Is your feature request related to a problem? Please describe.**
I am running a setup, where I have only one valve and a [mechanical auto-switch device](https://www.gardena.com/de/produkte/bewasserung/bewasserungssteuerung/wasserverteiler-automatic/966749301/) behind this valve. 
This mechanical switch is automatically starting at the first zone of my watering setup. As soon as the water pressure lowers, it automatically switches to the second, third, fourth "zone".
But like I said, the water pressure actually needs to lower (recommended by the manufacturer is for one minute), so it can switch to the next zone. 

This is currently not possible because the Plugin starts the zones directly after another one has ended
![image](https://user-images.githubusercontent.com/62359912/165539530-03bf1c7f-6b4d-431c-985d-a85738d56a3f.png)

**Describe the solution you'd like**
Adding a delay between the watering cycles (and / or zones) would solve the problem. 

And as the minimum runtime for one cycle would also be 1 Minute (For the Pressure inside the thing to build up), it would also require a minimum runtime...
But it would also make some scheduling situations impossible (i.e. not watering a zone for one day because the mechanic wouldn't skip a zone. It would just water the next, presumably wrong one (when the next zone starts)).

Maybe this is just kind out of focus for this Plugin?

**Comment by MTry** [comment]
Thank you for taking the time to suggest this feature request. I do have a few questions for you though..

Since you are using a device with mechanical auto-switching, how are you planning to control the subsequent zones with this plugin? From what I could understand on the linked device page and google-translate - the device itself offers the option to control the subsequent zone times and that is triggered by the starting and stopping for the first zone in the device. If the watering time of the mechanical auto-switch is determined at the switch itself, this plugin has limited role to play other than making the first trigger and not the watering time? If all you want is a trigger, perhaps the best solution could be a dummy switch which is set on a schedule through Home automation!? Am I missing something here?

Adding configurable delay(between zones as well as between cycles as per some other use cases) is less trivial than it initially sounds since it will involve recoding some calculations at multiple locations - since the plugin aims to conclude watering by a set time rather than simply start at a particular time and then run as long as needed. This is going to take some time unfortunately with my current schedule..

I could suggest a workaround specifically for your case though if my understanding of your situation is correct - intersperse your zones configuration in the plugin with dummy zones - and keep these dummy zones non-adaptive with a prefixed runtime of more than a minute - this could get your device to run properly. However I still don't understand how your mech auto-switching device's subsequent zone time will be controlled by this plugin.. will wait for you to shed some more light on that.

**Comment by TheRealSimonMlr** [comment]
Hey Mtry,
thank you for the response and your explanations.

Yea, I kind of figured out already, that I might be better off with one valve for each cycle, just because of "logical" operation and individual watering needs for the zones. Not so much because of the features from this plugin, just because of the physics of nature :D

Nevertheless, I figured out a way to add a "delay" via HomeKit Scenes (just switching off the valves when 85 seconds runtime is left).
Because I have sprinklers which require quite a long runtime, the missing seconds shouldn't be a problem.

Enough for a workaround, I guess for a pro-solution you have to have 1 valve for each cycle. 

In case anybody needs it:
Turning on:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/62359912/166296952-1e78c16a-b435-439a-9de2-f56b912a2ca5.png">


Turning off:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/62359912/166296827-cc62f6ff-b6ed-420b-a84a-193c19c53d0e.png">


Disabling Irrigation if any zone is scheduled for 90 seconds or less:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/62359912/166297086-a8811214-a4a8-482d-b1b3-afcc09fbc453.png">
