### ISSUE TITLE
When in Manuell Mode, Zones do not switch ooff after set time

### ISSUE THREAD

**Issue by bubffm** [MTry/homebridge-smart-irrigation#4]
I noticed something else.  

I have three zones, for each I set the standard time to 5mins.  When I active irrigation in any zone, I noticed that it does not switch off after 5 minutes.  I then noticed, this is probably because the "Master" counts down from 300 minutes!

I guess that might be a bug?

![IMG_0359](https://user-images.githubusercontent.com/49747999/115757602-c4644d00-a39e-11eb-8414-021ac8c93cf7.PNG)

**Comment by MTry** [comment]
This is the intended operation - the ability to shut off after the duration set from Homekit is inherent in valves, however in this case the plugin does not poll the set value and handle the remaining time in order to shut the valve off - it's logic currently is to leave the "manual" mode completely in user control. Essentially, it handles driving the valves as per the times calculated under the "Scheduled" mode - rather than handling the control when in Manual mode. As a matter of fact this is the reason I suggest that the "real valve" you are using should have a fail-safe "default" time set to a value somewhat higher than the longest duration you expect a single cycle of that zone to last

**Comment by MTry** [comment]
To add to the above, I would need to further go down the road where in case a use sets the time manually, I must force the system off the "Scheduled" mode into a "Manual" mode - cancel all schedules - and wait for some other input from the user to decide whether to use climate intelligence at all or not.. or wait for a check on next sunrise or another time to reenable schedules... gets kind of messy down this path!

**Comment by bubffm** [comment]
ok, thanks, understood!
